#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE}") && pwd)

# git
ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig
ln -sf $DOTFILES/git/gitignore $HOME/.gitignore

# kitty terminal
rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

# zsh
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

# idea
ln -sf $DOTFILES/idea/ideavimrc $HOME/.ideavimrc

# nvim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim
